### ISSUE TITLE
Column headers in Bridge_Building_Model_manual_output_v02

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/NW-synthesis#1]
When I run select.java with option 2 and various other inputs, Bridge_Building_Model_manual_output_v02.csv (along with network files) is generated as outputs. Could you please add column headers in Bridge_Building_Model_manual_output_v02.csv?

**Comment by manishjain2792** [comment]
Added header to the CSV file. But if you run the code again and again, then every time a single header generated. So , Shall I need to make only one header? 

I have done in this way just because we can understand the no. of execuation.

**Comment by dsubhaji** [comment]
Thanks!
