### ISSUE TITLE
Number of steps in varying a parameter

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/NW-synthesis#2]
Look at an example console output below when select.java is run:

*\* START **

Choose(Press 1 or 2):
1.Network Growth Model
2.Network Connection Model
2
Select the parameter which you want to vary over a range of values:
1.No of branches
2.Height
3.Probability of affiliation of leaf nodes under same parent
4.Given level?
5.Probability of affiliation at a given level
6.Random affiliation probability
6
You have selected Random Affiliation
Enter lower limit:
0.1
Enter upper limit:
0.9
No of branches? 
4
Height? 
5
Probability of affiliation of leaf nodes under same parent? 
0.5
Given level? 
2
Probability of affiliation at a given level? 
0.5
*\* END **

After the following inputs (for any parameter the user chooses to vary), ask the user - "Enter number of steps in increment between lower and upper limit" and on the basis of what the user enters, divide the range between lower and upper limit in equal increments of the steps and generate the networks accordingly. Also, mention the step numbers with the corresponding value of the varying parameter in the Bridge_Building_Model_manual_output_v02:

Enter lower limit:
0.1
Enter upper limit:
0.9

**Comment by manishjain2792** [comment]
Enhanced the code for variable steps.

**Comment by manishjain2792** [comment]
Fixed.

**Comment by dsubhaji** [comment]
Thanks!
