### ISSUE TITLE
Output folder name and contents for connection model

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/NW-synthesis#5]
1. Name the output folder as <time-stamp>-simulation-results so that we can easily differentiate output from different runs.
2. In addition to the Bridge_Building_Model_manual_output_v02.csv file and the network files, in the <time-stamp>-simulation-results folder there needs to be another inputs.txt file which captures all the user inputs, like:

Varying parameter: <value>
Upper limit: <value>
Lower limit: <value>
No of steps: <value>
Non varying parameters:
<Name>: <value>
<Name>: <value>
<Name>: <value>
<Name>: <value>
<Name>: <value>

As an example, for the following set of inputs:

Choose(Press 1 or 2):
1.Network Growth Model
2.Network Connection Model
2
Select the parameter which you want to vary over a range of values:
1.No of branches
2.Height
3.Probability of affiliation of leaf nodes under same parent
4.Given level?
5.Probability of affiliation at a given level
6.Random affiliation probability
5
dirName=C:\Users\subhajit_datta\Dropbox\my_things\dropbox_s_present_sutd\program\empirical-swe\NW-synthesis\simulation-results\

You have selected Probability of affiliation at a given level
Enter lower limit:
0
Enter upper limit:
1
Enter the steps
2
No of branches? 
2
Height? 
3
Probability of affiliation of leaf nodes under same parent? 
0
Given level? 
2
Random affiliation probability?
0

the input.txt file will be:

Varying parameter: 5. Probability of affiliation at a given level
Upper limit: 1
Lower limit: 0
No of steps: 2

Non varying parameters:
1.No of branches: 2
2.Height: 3
3.Probability of affiliation of leaf nodes under same parent: 0
4.Given level: 2
6.Random affiliation probability: 0

**Comment by manishjain2792** [comment]
Please have a look the changes for option 1.

**Comment by dsubhaji** [comment]
Thanks!
